---
title: "Main indicators"
output:
  html_document:
    theme: 
      bg: "#ffffff" 
      fg: "#7f7f7f"
      primary: "#4a5c83"
      base_font: !expr bslib::font_google("Outfit")
      heading_font: !expr bslib::font_google("Source Sans Pro")
      code_font: !expr bslib::font_google("Outfit")
      code-color: skyblue
      font-base-size: 1.25rem
params: 
    select_id: "24663185"
    region: "CMA"
    df: "DA"
    tileset_prefix: "mtl"
    scale_sing: "Dissemination area (count)"
    map_loc: c("lat", "lon")
    map_zoom: 13.75
    mapbox_username: "sus-mcgill"
    title_card_data: ""
---

```{css, echo=FALSE}
.bg-col_pe_1 {
  background-color:#CA002095;
  color:#ffffff
}

.bg-col_pe_2 {
  background-color:#F4A58295;
  color:#222222
}

.bg-col_pe_3 {
  background-color:#A9A9A995;
  color:#222222
}

.bg-col_pe_4 {
  background-color:#BAE4B395;
  color:#222222
}

.bg-col_pe_5 {
  background-color:#31A35495;
  color:#ffffff
}

```


```{r map, echo = FALSE}

# Decide which color for the map
hexes <- c("#CA002095", "#F4A58295", "#A9A9A995", "#BAE4B395", "#31A35495")
map_col <- hexes[mean(sapply(params$title_card_data, `[[`, "hex_cat"))]
map_col_light <- gsub("95$", "20", map_col)

# Necessary for the mapdeck
map_token <- paste0("pk.eyJ1Ijoic3VzLW1jZ2lsbCIsImEiOiJjbDBxMTcyNWwyNTl0M2",
                    "RtZzRremNxOHA3In0.V2Ah5lxy-3RZlF2QKOvIjg")
options(rdeck.mapbox_access_token = map_token)
map_style_building <- "mapbox://styles/sus-mcgill/cl2bwtrsp000516rwyrkt9ior"

rdeck::rdeck(map_style = map_style_building, initial_view_state = rdeck::view_state(
    center = params$map_loc, zoom = params$map_zoom), width = "100%", height = "200px") |>
    rdeck::add_mvt_layer(
        id = "study",
        data = rdeck::mvt_url(paste0(params$mapbox_username, ".", params$tileset_prefix, "_", params$region, "_", params$df)),
        pickable = FALSE,
        auto_highlight = FALSE,
        get_fill_color = rdeck::scale_color_category(
            col = ID,
            palette = c(map_col_light, "#BAE4B300"),
            unmapped_color = "#BAE4B300",
            levels = c(params$select_id, "NA"),
            legend = FALSE),
        get_line_color = rdeck::scale_color_category(
            col = ID,
            palette = c(map_col, "#BAE4B300"),
            unmapped_color = "#BAE4B300",
            levels = c(params$select_id, "NA"),
            legend = FALSE),
        line_width_units = "pixels",
        get_line_width = 5) |> suppressWarnings()

```

```{r plotlies, echo = FALSE}

vline <- function(x = 0) {
  list(
    type = "line",
    y0 = 0,
    y1 = 1,
    yref = "paper",
    x0 = x,
    x1 = x,
    line = list(color = "#222222")
  )
}

plotlies <- lapply(params$title_card_data, \(ind) {
  
  this_dat <- ind$data$var[ind$data$ID == params$select_id]
  
  plot <- plotly::plot_ly(ind$data)
  plot <- plotly::add_histogram(plot, x = ~var,
                                color = I("white"),
                                alpha = 0.75,
                                hoverinfo = "x")
  plot <- plotly::layout(
    plot,
    xaxis = list(visible = F, showgrid = F, title = ind$xaxis_title),
    yaxis = list(visible = F, showgrid = F, title = params$scale_sing),
    hovermode = "x",
    margin = list(t = 0, r = 0, l = 0, b = 0),
    font = list(color = "white"),
    paper_bgcolor = "transparent",
    plot_bgcolor = "transparent",
    shapes = list(vline(this_dat))
  )
  plot <-  plotly::config(plot, displayModeBar = F)
  plot <- htmlwidgets::onRender(plot, 
                                "function(el) {
      var ro = new ResizeObserver(function() {
         var visible = el.offsetHeight > 200;
         Plotly.relayout(el, {'xaxis.visible': visible});
         Plotly.relayout(el, {'yaxis.visible': visible});
      });
      ro.observe(el);
    }"
  )
})



```


```{r valueboxes, echo = FALSE, warning = FALSE}

boxes <- mapply(\(ind, ind_name) {
  bslib::value_box(
  title = htmltools::p(ind$row_title, bsicons::bs_icon(ind$bs_icon)),
  value = ind$percentile,
  showcase = plotlies[[ind_name]],
  htmltools::p(htmltools::HTML(ind$text)),
  full_screen = TRUE,
  theme_color = paste0("col_pe_", ind$hex_cat)
)
}, params$title_card_data, names(params$title_card_data), SIMPLIFY = FALSE)

do.call(bslib::layout_column_wrap, c(list(width = 1/2), unname(boxes)))

```

